spring.application.name=spring-ai-demo
gemini.api.url= ${GEMINI_API_URL}
gemini.api.key= ${GEMINI_API_KEY}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

gemini.extraction.prompt=${EXTRACTION_PROMPT_V1}